name: Building for RUT 900, 905, 950, 955

on:
  release:
    types: [created, tagged]
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Prepare IPK package
      run: |
        mkdir -p `pwd`/build/etc/init.d
        mkdir -p `pwd`/build/etc/config
        cp -a openwrt/CONTROL `pwd`/build
        cp openwrt/omg.init `pwd`/build/etc/init.d/omg
        cp openwrt/omg.config `pwd`/build/etc/config/omg
        chmod +x `pwd`/build/etc/init.d/omg
        echo "Architecture: mips_24kc" >> build/CONTROL/control

    - name: Build project with Teltonika SDK Toolchain (RUT9_R 900, 905, 950, 955)
      uses: docker://ganehag/teltonika-sdk-toolchain:RUT9_R_00.07.03.4
      with:
        args: bash -c "export PATH=/opt/toolchain-mips_24kc_gcc-8.4.0_musl/bin:$PATH; ./configure --host=mips-openwrt-linux-musl --prefix=`pwd`/build/usr && make install"

    - name: "Build IPK package"
      uses: docker://ganehag/teltonika-sdk-toolchain:RUT9_R_00.07.03.4
      with:
        args: ipk-build build .

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: omg_*.ipk
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
